# Create a new task
POST http://localhost:3333/api/task HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I3MGUzZjU2ZTcxYjQ1ZDNkNzMwNDkiLCJlbWFpbCI6ImVydHlAZ21haWwuY29tIiwicm9sZSI6ItCX0LDQutCw0LfRh9C40LoiLCJuYW1lIjoiQ2hpcCBIYXdrIiwiaWF0IjoxNjcyOTg2OTc3LCJleHAiOjE2NzI5OTI5Nzd9.SWVBQVzrx79jDrkzl_3kVf-LvSR6ancqi-KMhzgXrxg

{
  "title": "Hello world!",
  "description": "Расширенный текст публикации",
  "category": [1]
}

### Delete task
DELETE http://localhost:3333/api/task/45 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I3MGUzZjU2ZTcxYjQ1ZDNkNzMwNDkiLCJlbWFpbCI6ImVydHlAZ21haWwuY29tIiwicm9sZSI6ItCX0LDQutCw0LfRh9C40LoiLCJuYW1lIjoiQ2hpcCBIYXdrIiwiaWF0IjoxNjcyOTkzMDA1LCJleHAiOjE2NzI5OTkwMDV9.ZBZqSQsidtiQJXn9uw8H3DqrrhqYXIBf1b-8rEqyj9U

### Find task
GET http://localhost:3333/api/task/45 HTTP/1.1
