### Find user
GET http://localhost:3333/api/user/63b68944c32dbbb797ce0a22 HTTP/1.1

### Edit user profile
PATCH http://localhost:3333/api/user/63b68944c32dbbb797ce0a22 HTTP/1.1
Content-Type: application/json

{
  "name": "Hawk Chip",
  "specialization": ["Manager", "Manager"]
}
