### Find user
GET http://localhost:3333/api/user/ec22b4e9-f63c-4d37-aa30-a70d9f7058a6 HTTP/1.1

### Update user password
PATCH http://localhost:3333/api/user/ec22b4e9-f63c-4d37-aa30-a70d9f7058a6 HTTP/1.1
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "654321"
}
