### Create user
POST http://localhost:3334/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "ddhip Hawk",
  "email": "tty@gmail.com",
  "city": "Москва",
  "passwordHash": "123456",
  "role": "Исполнитель",
  "dateBirth": "2000-05-14",
  "sendNotify": true
}

### Login user
POST http://localhost:3334/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "erty@gmail.com",
  "passwordHash": "123456"
}

### Update user password
PATCH http://localhost:3334/api/auth/63b6ad01f46df378971e0dd6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2I2YWQwMWY0NmRmMzc4OTcxZTBkZDYiLCJlbWFpbCI6IndlcnR5QGdtYWlsLmNvbSIsInJvbGUiOiLQmNGB0L_QvtC70L3QuNGC0LXQu9GMIiwibmFtZSI6Ikhhd2sgQ2hpcCIsImlhdCI6MTY3Mjk0NTk1NCwiZXhwIjoxNjcyOTU3OTU0fQ.NHltXxi8YjKhJJ_1_Jqyf8vaD_eczoliDRp20fdsRVc

{
  "currentPassword": "123456",
  "newPassword": "123456"
}
