### Create user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Chip Hawk",
  "email": "werty@gmail.com",
  "city": "Москва",
  "passwordHash": "123456",
  "role": "Исполнитель",
  "avatar": "silicon.jpg",
  "dateBirth": "2000-05-14"
}

### Login user
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "qwerty@gmail.com",
  "passwordHash": "123456"
}
